SNIFF_SPOT_WATCHES = {
    { addr = 0x7e228c, len = 0x25 },
    { addr = 0x7e22b2, len = 0x27 },
}
SNIFF_MAPPING_DETAILED = {
    [0x7E228F] = {
        [0x10] = { "@Sniff Spot #0/(Vanilla: Clay)" },
        [0x08] = { "@Sniff Spot #13/(Vanilla: Clay)" },
        [0x20] = { "@Sniff Spot #17/(Vanilla: Root)" },
        [0x80] = { "@Sniff Spot #18/(Vanilla: Root)" },
        [0x40] = { "@Sniff Spot #23/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #235/(Vanilla: Water)" },
        [0x02] = { "@Sniff Spot #264/(Vanilla: Oil)" },
    },
    [0x7E2291] = {
        [0x02] = { "@Sniff Spot #1/(Vanilla: Ash)" },
        [0x01] = { "@Sniff Spot #4/(Vanilla: Ash)" },
        [0x80] = { "@Sniff Spot #10/(Vanilla: Water)" },
        [0x40] = { "@Sniff Spot #11/(Vanilla: Water)" },
        [0x20] = { "@Sniff Spot #14/(Vanilla: Water)" },
        [0x08] = { "@Sniff Spot #16/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #20/(Vanilla: Water)" },
        [0x10] = { "@Sniff Spot #22/(Vanilla: Water)" },
    },
    [0x7E2290] = {
        [0x10] = { "@Sniff Spot #2/(Vanilla: Root)" },
        [0x80] = { "@Sniff Spot #5/(Vanilla: Ash)" },
        [0x08] = { "@Sniff Spot #9/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #12/(Vanilla: Root)" },
        [0x02] = { "@Sniff Spot #15/(Vanilla: Root)" },
        [0x40] = { "@Sniff Spot #19/(Vanilla: Ash)" },
        [0x01] = { "@Sniff Spot #21/(Vanilla: Root)" },
    },
    [0x7E2292] = {
        [0x08] = { "@Sniff Spot #3/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #6/(Vanilla: Water)" },
        [0x02] = { "@Sniff Spot #7/(Vanilla: Water)" },
        [0x01] = { "@Sniff Spot #8/(Vanilla: Water)" },
        [0x20] = { "@Sniff Spot #43/(Vanilla: Ash)" },
        [0x40] = { "@Sniff Spot #44/(Vanilla: Ash)" },
        [0x80] = { "@Sniff Spot #45/(Vanilla: Ash)" },
    },
    [0x7E2293] = {
        [0x08] = { "@Sniff Spot #31/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #32/(Vanilla: Water)" },
        [0x80] = { "@Sniff Spot #36/(Vanilla: Oil)" },
        [0x02] = { "@Sniff Spot #37/(Vanilla: Water)" },
        [0x40] = { "@Sniff Spot #38/(Vanilla: Oil)" },
        [0x01] = { "@Sniff Spot #39/(Vanilla: Water)" },
        [0x20] = { "@Sniff Spot #41/(Vanilla: Oil)" },
        [0x10] = { "@Sniff Spot #42/(Vanilla: Water)" },
    },
    [0x7E2294] = {
        [0x10] = { "@Sniff Spot #33/(Vanilla: Root)" },
        [0x08] = { "@Sniff Spot #34/(Vanilla: Root)" },
        [0x01] = { "@Sniff Spot #35/(Vanilla: Oil)" },
        [0x04] = { "@Sniff Spot #40/(Vanilla: Root)" },
        [0x80] = { "@Sniff Spot #52/(Vanilla: Root)" },
        [0x40] = { "@Sniff Spot #57/(Vanilla: Root)" },
        [0x20] = { "@Sniff Spot #58/(Vanilla: Root)" },
    },
    [0x7E2296] = {
        [0x04] = { "@Sniff Spot #47/(Vanilla: Clay)" },
        [0x02] = { "@Sniff Spot #48/(Vanilla: Clay)" },
        [0x01] = { "@Sniff Spot #49/(Vanilla: Clay)" },
        [0x08] = { "@Sniff Spot #65/(Vanilla: Ash)" },
        [0x10] = { "@Sniff Spot #66/(Vanilla: Ash)" },
        [0x20] = { "@Sniff Spot #67/(Vanilla: Ash)" },
        [0x40] = { "@Sniff Spot #68/(Vanilla: Ash)" },
        [0x80] = { "@Sniff Spot #69/(Vanilla: Ash)" },
    },
    [0x7E2295] = {
        [0x02] = { "@Sniff Spot #50/(Vanilla: Root)" },
        [0x01] = { "@Sniff Spot #51/(Vanilla: Root)" },
        [0x40] = { "@Sniff Spot #53/(Vanilla: Water)" },
        [0x20] = { "@Sniff Spot #54/(Vanilla: Water)" },
        [0x10] = { "@Sniff Spot #55/(Vanilla: Water)" },
        [0x08] = { "@Sniff Spot #56/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #59/(Vanilla: Water)" },
        [0x80] = { "@Sniff Spot #60/(Vanilla: Clay)" },
    },
    [0x7E2297] = {
        [0x20] = { "@Sniff Spot #61/(Vanilla: Wax)" },
        [0x10] = { "@Sniff Spot #62/(Vanilla: Wax)" },
        [0x08] = { "@Sniff Spot #63/(Vanilla: Wax)" },
        [0x04] = { "@Sniff Spot #64/(Vanilla: Wax)" },
        [0x01] = { "@Sniff Spot #70/(Vanilla: Ash)" },
        [0x02] = { "@Sniff Spot #71/(Vanilla: Ash)" },
        [0x40] = { "@Sniff Spot #72/(Vanilla: Root)" },
        [0x80] = { "@Sniff Spot #73/(Vanilla: Root)" },
    },
    [0x7E2298] = {
        [0x01] = { "@Sniff Spot #74/(Vanilla: Root)" },
        [0x02] = { "@Sniff Spot #75/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #76/(Vanilla: Root)" },
        [0x08] = { "@Sniff Spot #77/(Vanilla: Clay)" },
        [0x10] = { "@Sniff Spot #78/(Vanilla: Clay)" },
        [0x20] = { "@Sniff Spot #79/(Vanilla: Clay)" },
        [0x80] = { "@Sniff Spot #80/(Vanilla: Clay)" },
    },
    [0x7E2299] = {
        [0x01] = { "@Sniff Spot #81/(Vanilla: Oil)" },
        [0x02] = { "@Sniff Spot #82/(Vanilla: Oil)" },
        [0x04] = { "@Sniff Spot #83/(Vanilla: Oil)" },
        [0x08] = { "@Sniff Spot #84/(Vanilla: Oil)" },
        [0x10] = { "@Sniff Spot #85/(Vanilla: Oil)" },
        [0x20] = { "@Sniff Spot #86/(Vanilla: Oil)" },
        [0x40] = { "@Sniff Spot #87/(Vanilla: Oil)" },
        [0x80] = { "@Sniff Spot #88/(Vanilla: Oil)" },
    },
    [0x7E229A] = {
        [0x01] = { "@Sniff Spot #89/(Vanilla: Root)" },
        [0x02] = { "@Sniff Spot #90/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #91/(Vanilla: Root)" },
        [0x08] = { "@Sniff Spot #92/(Vanilla: Root)" },
        [0x10] = { "@Sniff Spot #93/(Vanilla: Root)" },
        [0x20] = { "@Sniff Spot #94/(Vanilla: Root)" },
        [0x40] = { "@Sniff Spot #95/(Vanilla: Root)" },
        [0x80] = { "@Sniff Spot #96/(Vanilla: Ash)" },
    },
    [0x7E229B] = {
        [0x01] = { "@Sniff Spot #97/(Vanilla: Ash)" },
        [0x02] = { "@Sniff Spot #98/(Vanilla: Ash)" },
        [0x04] = { "@Sniff Spot #99/(Vanilla: Ash)" },
        [0x08] = { "@Sniff Spot #100/(Vanilla: Ash)" },
        [0x10] = { "@Sniff Spot #101/(Vanilla: Crystal)" },
        [0x20] = { "@Sniff Spot #103/(Vanilla: Crystal)" },
        [0x40] = { "@Sniff Spot #104/(Vanilla: Crystal)" },
        [0x80] = { "@Sniff Spot #105/(Vanilla: Clay)" },
    },
    [0x7E229C] = {
        [0x08] = { "@Sniff Spot #102/(Vanilla: Wax)" },
        [0x01] = { "@Sniff Spot #106/(Vanilla: Clay)" },
        [0x02] = { "@Sniff Spot #107/(Vanilla: Clay)" },
        [0x04] = { "@Sniff Spot #108/(Vanilla: Clay)" },
        [0x10] = { "@Sniff Spot #109/(Vanilla: Wax)" },
        [0x20] = { "@Sniff Spot #110/(Vanilla: Wax)" },
        [0x40] = { "@Sniff Spot #111/(Vanilla: Wax)" },
        [0x80] = { "@Sniff Spot #112/(Vanilla: Wax)" },
    },
    [0x7E229D] = {
        [0x01] = { "@Sniff Spot #113/(Vanilla: Wax)" },
        [0x02] = { "@Sniff Spot #114/(Vanilla: Wax)" },
        [0x04] = { "@Sniff Spot #115/(Vanilla: Water)" },
        [0x08] = { "@Sniff Spot #116/(Vanilla: Water)" },
        [0x10] = { "@Sniff Spot #117/(Vanilla: Clay)" },
        [0x20] = { "@Sniff Spot #118/(Vanilla: Clay)" },
        [0x40] = { "@Sniff Spot #119/(Vanilla: Clay)" },
        [0x80] = { "@Sniff Spot #120/(Vanilla: Clay)" },
    },
    [0x7E229E] = {
        [0x01] = { "@Sniff Spot #121/(Vanilla: Clay)" },
        [0x02] = { "@Sniff Spot #122/(Vanilla: Clay)" },
        [0x04] = { "@Sniff Spot #123/(Vanilla: Root)" },
        [0x08] = { "@Sniff Spot #124/(Vanilla: Root)" },
        [0x20] = { "@Sniff Spot #125/(Vanilla: Root)" },
        [0x10] = { "@Sniff Spot #126/(Vanilla: Root)" },
        [0x40] = { "@Sniff Spot #127/(Vanilla: Oil)" },
        [0x80] = { "@Sniff Spot #128/(Vanilla: Oil)" },
    },
    [0x7E229F] = {
        [0x01] = { "@Sniff Spot #129/(Vanilla: Oil)" },
        [0x02] = { "@Sniff Spot #130/(Vanilla: Oil)" },
        [0x04] = { "@Sniff Spot #131/(Vanilla: Oil)" },
        [0x08] = { "@Sniff Spot #132/(Vanilla: Oil)" },
        [0x10] = { "@Sniff Spot #133/(Vanilla: Oil)" },
        [0x20] = { "@Sniff Spot #134/(Vanilla: Oil)" },
        [0x40] = { "@Sniff Spot #135/(Vanilla: Ash)" },
        [0x80] = { "@Sniff Spot #136/(Vanilla: Ash)" },
    },
    [0x7E22A0] = {
        [0x01] = { "@Sniff Spot #137/(Vanilla: Ash)" },
        [0x02] = { "@Sniff Spot #138/(Vanilla: Ash)" },
        [0x04] = { "@Sniff Spot #139/(Vanilla: Water)" },
        [0x08] = { "@Sniff Spot #140/(Vanilla: Water)" },
        [0x10] = { "@Sniff Spot #141/(Vanilla: Water)" },
        [0x20] = { "@Sniff Spot #142/(Vanilla: Clay)" },
        [0x40] = { "@Sniff Spot #143/(Vanilla: Clay)" },
        [0x80] = { "@Sniff Spot #144/(Vanilla: Clay)" },
    },
    [0x7E22A1] = {
        [0x01] = { "@Sniff Spot #145/(Vanilla: Root)" },
        [0x02] = { "@Sniff Spot #146/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #147/(Vanilla: Root)" },
        [0x08] = { "@Sniff Spot #148/(Vanilla: Oil)" },
        [0x10] = { "@Sniff Spot #149/(Vanilla: Oil)" },
        [0x20] = { "@Sniff Spot #150/(Vanilla: Oil)" },
        [0x40] = { "@Sniff Spot #151/(Vanilla: Water)" },
        [0x80] = { "@Sniff Spot #152/(Vanilla: Water)" },
    },
    [0x7E22A2] = {
        [0x01] = { "@Sniff Spot #153/(Vanilla: Water)" },
        [0x02] = { "@Sniff Spot #154/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #155/(Vanilla: Water)" },
        [0x08] = { "@Sniff Spot #156/(Vanilla: Water)" },
        [0x10] = { "@Sniff Spot #157/(Vanilla: Oil)" },
        [0x20] = { "@Sniff Spot #158/(Vanilla: Oil)" },
        [0x40] = { "@Sniff Spot #159/(Vanilla: Root)" },
        [0x80] = { "@Sniff Spot #160/(Vanilla: Root)" },
    },
    [0x7E22A3] = {
        [0x01] = { "@Sniff Spot #161/(Vanilla: Root)" },
        [0x02] = { "@Sniff Spot #162/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #163/(Vanilla: Root)" },
        [0x08] = { "@Sniff Spot #164/(Vanilla: Clay)" },
        [0x10] = { "@Sniff Spot #165/(Vanilla: Clay)" },
        [0x20] = { "@Sniff Spot #166/(Vanilla: Clay)" },
        [0x40] = { "@Sniff Spot #167/(Vanilla: Ash)" },
        [0x80] = { "@Sniff Spot #168/(Vanilla: Ash)" },
    },
    [0x7E22A4] = {
        [0x01] = { "@Sniff Spot #169/(Vanilla: Ash)" },
        [0x02] = { "@Sniff Spot #170/(Vanilla: Wax)" },
        [0x04] = { "@Sniff Spot #171/(Vanilla: Wax)" },
        [0x80] = { "@Sniff Spot #183/(Vanilla: Clay)" },
        [0x10] = { "@Sniff Spot #189/(Vanilla: Water)" },
        [0x08] = { "@Sniff Spot #190/(Vanilla: Water)" },
        [0x20] = { "@Sniff Spot #194/(Vanilla: Water)" },
        [0x40] = { "@Sniff Spot #197/(Vanilla: Water)" },
    },
    [0x7E22A7] = {
        [0x10] = { "@Sniff Spot #172/(Vanilla: Ash)" },
        [0x08] = { "@Sniff Spot #174/(Vanilla: Ash)" },
        [0x02] = { "@Sniff Spot #175/(Vanilla: Ash)" },
        [0x01] = { "@Sniff Spot #176/(Vanilla: Ash)" },
        [0x04] = { "@Sniff Spot #177/(Vanilla: Ash)" },
        [0x80] = { "@Sniff Spot #179/(Vanilla: Wax)" },
        [0x40] = { "@Sniff Spot #181/(Vanilla: Ash)" },
        [0x20] = { "@Sniff Spot #200/(Vanilla: Ash)" },
    },
    [0x7E22A6] = {
        [0x40] = { "@Sniff Spot #173/(Vanilla: Oil)" },
        [0x80] = { "@Sniff Spot #180/(Vanilla: Ash)" },
        [0x10] = { "@Sniff Spot #184/(Vanilla: Oil)" },
        [0x04] = { "@Sniff Spot #185/(Vanilla: Root)" },
        [0x20] = { "@Sniff Spot #187/(Vanilla: Oil)" },
        [0x08] = { "@Sniff Spot #191/(Vanilla: Oil)" },
        [0x02] = { "@Sniff Spot #193/(Vanilla: Root)" },
        [0x01] = { "@Sniff Spot #198/(Vanilla: Root)" },
    },
    [0x7E22A8] = {
        [0x01] = { "@Sniff Spot #178/(Vanilla: Wax)" },
        [0x02] = { "@Sniff Spot #202/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #203/(Vanilla: Water)" },
        [0x08] = { "@Sniff Spot #204/(Vanilla: Water)" },
        [0x10] = { "@Sniff Spot #205/(Vanilla: Water)" },
        [0x20] = { "@Sniff Spot #206/(Vanilla: Water)" },
        [0x40] = { "@Sniff Spot #207/(Vanilla: Water)" },
        [0x80] = { "@Sniff Spot #208/(Vanilla: Water)" },
    },
    [0x7E22A5] = {
        [0x02] = { "@Sniff Spot #182/(Vanilla: Clay)" },
        [0x40] = { "@Sniff Spot #186/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #188/(Vanilla: Clay)" },
        [0x80] = { "@Sniff Spot #192/(Vanilla: Root)" },
        [0x01] = { "@Sniff Spot #195/(Vanilla: Clay)" },
        [0x20] = { "@Sniff Spot #196/(Vanilla: Root)" },
        [0x10] = { "@Sniff Spot #199/(Vanilla: Clay)" },
        [0x08] = { "@Sniff Spot #201/(Vanilla: Clay)" },
    },
    [0x7E22A9] = {
        [0x01] = { "@Sniff Spot #209/(Vanilla: Water)" },
        [0x02] = { "@Sniff Spot #210/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #211/(Vanilla: Clay)" },
        [0x08] = { "@Sniff Spot #212/(Vanilla: Clay)" },
        [0x10] = { "@Sniff Spot #213/(Vanilla: Clay)" },
        [0x40] = { "@Sniff Spot #214/(Vanilla: Clay)" },
        [0x20] = { "@Sniff Spot #215/(Vanilla: Clay)" },
        [0x80] = { "@Sniff Spot #216/(Vanilla: Clay)" },
    },
    [0x7E22AA] = {
        [0x01] = { "@Sniff Spot #217/(Vanilla: Clay)" },
        [0x80] = { "@Sniff Spot #218/(Vanilla: Root)" },
        [0x40] = { "@Sniff Spot #219/(Vanilla: Root)" },
        [0x20] = { "@Sniff Spot #220/(Vanilla: Root)" },
        [0x10] = { "@Sniff Spot #221/(Vanilla: Root)" },
        [0x08] = { "@Sniff Spot #222/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #223/(Vanilla: Root)" },
        [0x02] = { "@Sniff Spot #224/(Vanilla: Root)" },
    },
    [0x7E22AB] = {
        [0x01] = { "@Sniff Spot #225/(Vanilla: Oil)" },
        [0x02] = { "@Sniff Spot #226/(Vanilla: Oil)" },
        [0x04] = { "@Sniff Spot #227/(Vanilla: Ash)" },
        [0x08] = { "@Sniff Spot #228/(Vanilla: Ash)" },
        [0x80] = { "@Sniff Spot #283/(Vanilla: Water)" },
    },
    [0x7E22B3] = {
        [0x01] = { "@Sniff Spot #229/(Vanilla: Water)" },
        [0x80] = { "@Sniff Spot #230/(Vanilla: Wax)" },
        [0x40] = { "@Sniff Spot #231/(Vanilla: Oil)" },
        [0x20] = { "@Sniff Spot #232/(Vanilla: Oil)" },
        [0x10] = { "@Sniff Spot #234/(Vanilla: Root)" },
        [0x02] = { "@Sniff Spot #236/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #237/(Vanilla: Root)" },
        [0x08] = { "@Sniff Spot #238/(Vanilla: Root)" },
    },
    [0x7E22B2] = {
        [0x80] = { "@Sniff Spot #233/(Vanilla: Water)" },
    },
    [0x7E22B4] = {
        [0x01] = { "@Sniff Spot #239/(Vanilla: Wax)" },
        [0x20] = { "@Sniff Spot #372/(Vanilla: Ethanol)" },
        [0x40] = { "@Sniff Spot #373/(Vanilla: Ethanol)" },
        [0x80] = { "@Sniff Spot #374/(Vanilla: Ethanol)" },
    },
    [0x7E228E] = {
        [0x20] = { "@Sniff Spot #240/(Vanilla: Oil)" },
        [0x40] = { "@Sniff Spot #252/(Vanilla: Oil)" },
        [0x01] = { "@Sniff Spot #253/(Vanilla: Root)" },
        [0x02] = { "@Sniff Spot #254/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #255/(Vanilla: Root)" },
        [0x80] = { "@Sniff Spot #258/(Vanilla: Oil)" },
        [0x08] = { "@Sniff Spot #259/(Vanilla: Root)" },
        [0x10] = { "@Sniff Spot #260/(Vanilla: Root)" },
    },
    [0x7E228C] = {
        [0x04] = { "@Sniff Spot #241/(Vanilla: Water)" },
        [0x01] = { "@Sniff Spot #244/(Vanilla: Water)" },
        [0x02] = { "@Sniff Spot #245/(Vanilla: Water)" },
        [0x08] = { "@Sniff Spot #247/(Vanilla: Water)" },
        [0x10] = { "@Sniff Spot #248/(Vanilla: Water)" },
        [0x20] = { "@Sniff Spot #250/(Vanilla: Water)" },
        [0x40] = { "@Sniff Spot #251/(Vanilla: Water)" },
        [0x80] = { "@Sniff Spot #256/(Vanilla: Water)" },
    },
    [0x7E228D] = {
        [0x10] = { "@Sniff Spot #242/(Vanilla: Root)" },
        [0x20] = { "@Sniff Spot #243/(Vanilla: Root)" },
        [0x40] = { "@Sniff Spot #246/(Vanilla: Root)" },
        [0x80] = { "@Sniff Spot #249/(Vanilla: Root)" },
        [0x02] = { "@Sniff Spot #261/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #262/(Vanilla: Water)" },
        [0x08] = { "@Sniff Spot #263/(Vanilla: Water)" },
    },
    [0x7E22B0] = {
        [0x04] = { "@Sniff Spot #265/(Vanilla: Ash)" },
        [0x01] = { "@Sniff Spot #274/(Vanilla: Oil)" },
        [0x02] = { "@Sniff Spot #275/(Vanilla: Oil)" },
        [0x08] = { "@Sniff Spot #276/(Vanilla: Wax)" },
        [0x10] = { "@Sniff Spot #277/(Vanilla: Wax)" },
        [0x20] = { "@Sniff Spot #278/(Vanilla: Wax)" },
    },
    [0x7E22AF] = {
        [0x01] = { "@Sniff Spot #266/(Vanilla: Water)" },
        [0x02] = { "@Sniff Spot #267/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #268/(Vanilla: Clay)" },
        [0x08] = { "@Sniff Spot #269/(Vanilla: Root)" },
        [0x10] = { "@Sniff Spot #270/(Vanilla: Root)" },
        [0x20] = { "@Sniff Spot #271/(Vanilla: Root)" },
        [0x40] = { "@Sniff Spot #272/(Vanilla: Root)" },
        [0x80] = { "@Sniff Spot #273/(Vanilla: Oil)" },
    },
    [0x7E22AC] = {
        [0x08] = { "@Sniff Spot #279/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #280/(Vanilla: Water)" },
        [0x02] = { "@Sniff Spot #281/(Vanilla: Water)" },
        [0x01] = { "@Sniff Spot #282/(Vanilla: Water)" },
        [0x10] = { "@Sniff Spot #284/(Vanilla: Clay)" },
        [0x20] = { "@Sniff Spot #285/(Vanilla: Clay)" },
        [0x40] = { "@Sniff Spot #286/(Vanilla: Clay)" },
        [0x80] = { "@Sniff Spot #287/(Vanilla: Clay)" },
    },
    [0x7E22AD] = {
        [0x01] = { "@Sniff Spot #288/(Vanilla: Clay)" },
        [0x02] = { "@Sniff Spot #289/(Vanilla: Clay)" },
        [0x04] = { "@Sniff Spot #290/(Vanilla: Clay)" },
        [0x08] = { "@Sniff Spot #291/(Vanilla: Root)" },
        [0x10] = { "@Sniff Spot #292/(Vanilla: Oil)" },
        [0x20] = { "@Sniff Spot #293/(Vanilla: Oil)" },
        [0x40] = { "@Sniff Spot #294/(Vanilla: Ash)" },
        [0x80] = { "@Sniff Spot #295/(Vanilla: Ash)" },
    },
    [0x7E22AE] = {
        [0x01] = { "@Sniff Spot #296/(Vanilla: Ash)" },
        [0x02] = { "@Sniff Spot #297/(Vanilla: Ash)" },
        [0x04] = { "@Sniff Spot #298/(Vanilla: Ash)" },
        [0x08] = { "@Sniff Spot #299/(Vanilla: Ash)" },
        [0x10] = { "@Sniff Spot #300/(Vanilla: Ash)" },
        [0x20] = { "@Sniff Spot #301/(Vanilla: Wax)" },
        [0x40] = { "@Sniff Spot #302/(Vanilla: Wax)" },
        [0x80] = { "@Sniff Spot #303/(Vanilla: Wax)" },
    },
    [0x7E22D3] = {
        [0x08] = { "@Sniff Spot #313/(Vanilla: Clay)" },
        [0x04] = { "@Sniff Spot #314/(Vanilla: Ash)" },
        [0x20] = { "@Sniff Spot #315/(Vanilla: Oil)" },
        [0x10] = { "@Sniff Spot #316/(Vanilla: Oil)" },
        [0x01] = { "@Sniff Spot #358/(Vanilla: Vinegar)" },
        [0x02] = { "@Sniff Spot #359/(Vanilla: Bone)" },
        [0x80] = { "@Sniff Spot #579/(Vanilla: Iron)" },
        [0x40] = { "@Sniff Spot #580/(Vanilla: Iron)" },
    },
    [0x7E22D1] = {
        [0x01] = { "@Sniff Spot #317/(Vanilla: Water)" },
        [0x02] = { "@Sniff Spot #318/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #319/(Vanilla: Limestone)" },
        [0x08] = { "@Sniff Spot #320/(Vanilla: Limestone)" },
        [0x10] = { "@Sniff Spot #346/(Vanilla: Ethanol)" },
        [0x20] = { "@Sniff Spot #347/(Vanilla: Ethanol)" },
        [0x40] = { "@Sniff Spot #348/(Vanilla: Root)" },
        [0x80] = { "@Sniff Spot #349/(Vanilla: Root)" },
    },
    [0x7E22D0] = {
        [0x80] = { "@Sniff Spot #321/(Vanilla: Vinegar)" },
        [0x40] = { "@Sniff Spot #322/(Vanilla: Limestone)" },
        [0x20] = { "@Sniff Spot #323/(Vanilla: Bone)" },
        [0x10] = { "@Sniff Spot #324/(Vanilla: Bone)" },
        [0x08] = { "@Sniff Spot #325/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #326/(Vanilla: Root)" },
        [0x02] = { "@Sniff Spot #327/(Vanilla: Water)" },
        [0x01] = { "@Sniff Spot #330/(Vanilla: Water)" },
    },
    [0x7E22CF] = {
        [0x40] = { "@Sniff Spot #328/(Vanilla: Vinegar)" },
        [0x20] = { "@Sniff Spot #329/(Vanilla: Vinegar)" },
        [0x80] = { "@Sniff Spot #331/(Vanilla: Water)" },
        [0x08] = { "@Sniff Spot #542/(Vanilla: Ethanol)" },
        [0x04] = { "@Sniff Spot #543/(Vanilla: Ethanol)" },
        [0x02] = { "@Sniff Spot #544/(Vanilla: Ethanol)" },
        [0x01] = { "@Sniff Spot #545/(Vanilla: Ethanol)" },
    },
    [0x7E22B6] = {
        [0x08] = { "@Sniff Spot #332/(Vanilla: Water)" },
        [0x10] = { "@Sniff Spot #333/(Vanilla: Water)" },
        [0x20] = { "@Sniff Spot #334/(Vanilla: Water)" },
        [0x40] = { "@Sniff Spot #335/(Vanilla: Oil)" },
        [0x80] = { "@Sniff Spot #336/(Vanilla: Oil)" },
        [0x01] = { "@Sniff Spot #383/(Vanilla: Bone)" },
        [0x02] = { "@Sniff Spot #384/(Vanilla: Brimstone)" },
        [0x04] = { "@Sniff Spot #385/(Vanilla: Brimstone)" },
    },
    [0x7E22B7] = {
        [0x01] = { "@Sniff Spot #337/(Vanilla: Crystal)" },
        [0x02] = { "@Sniff Spot #338/(Vanilla: Crystal)" },
        [0x04] = { "@Sniff Spot #339/(Vanilla: Clay)" },
        [0x08] = { "@Sniff Spot #340/(Vanilla: Clay)" },
        [0x10] = { "@Sniff Spot #341/(Vanilla: Clay)" },
        [0x20] = { "@Sniff Spot #342/(Vanilla: Vinegar)" },
        [0x40] = { "@Sniff Spot #343/(Vanilla: Vinegar)" },
        [0x80] = { "@Sniff Spot #344/(Vanilla: Vinegar)" },
    },
    [0x7E22B8] = {
        [0x01] = { "@Sniff Spot #345/(Vanilla: Atlas Medallion)" },
        [0x80] = { "@Sniff Spot #435/(Vanilla: Limestone)" },
        [0x40] = { "@Sniff Spot #436/(Vanilla: Limestone)" },
        [0x20] = { "@Sniff Spot #437/(Vanilla: Limestone)" },
        [0x10] = { "@Sniff Spot #438/(Vanilla: Brimstone)" },
        [0x08] = { "@Sniff Spot #439/(Vanilla: Brimstone)" },
        [0x04] = { "@Sniff Spot #440/(Vanilla: Brimstone)" },
        [0x02] = { "@Sniff Spot #441/(Vanilla: Brimstone)" },
    },
    [0x7E22D2] = {
        [0x01] = { "@Sniff Spot #350/(Vanilla: Root)" },
        [0x02] = { "@Sniff Spot #351/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #352/(Vanilla: Limestone)" },
        [0x08] = { "@Sniff Spot #353/(Vanilla: Limestone)" },
        [0x10] = { "@Sniff Spot #354/(Vanilla: Wax)" },
        [0x20] = { "@Sniff Spot #355/(Vanilla: Wax)" },
        [0x40] = { "@Sniff Spot #356/(Vanilla: Water)" },
        [0x80] = { "@Sniff Spot #357/(Vanilla: Vinegar)" },
    },
    [0x7E22C1] = {
        [0x80] = { "@Sniff Spot #360/(Vanilla: Water)" },
        [0x40] = { "@Sniff Spot #361/(Vanilla: Water)" },
        [0x20] = { "@Sniff Spot #362/(Vanilla: Root)" },
        [0x10] = { "@Sniff Spot #363/(Vanilla: Ash)" },
        [0x08] = { "@Sniff Spot #364/(Vanilla: Wax)" },
        [0x04] = { "@Sniff Spot #365/(Vanilla: Brimstone)" },
        [0x02] = { "@Sniff Spot #366/(Vanilla: Brimstone)" },
        [0x01] = { "@Sniff Spot #367/(Vanilla: Limestone)" },
    },
    [0x7E22C0] = {
        [0x80] = { "@Sniff Spot #368/(Vanilla: Limestone)" },
        [0x40] = { "@Sniff Spot #369/(Vanilla: Vinegar)" },
        [0x20] = { "@Sniff Spot #370/(Vanilla: Ethanol)" },
        [0x10] = { "@Sniff Spot #371/(Vanilla: Ethanol)" },
        [0x08] = { "@Sniff Spot #442/(Vanilla: Brimstone)" },
        [0x04] = { "@Sniff Spot #443/(Vanilla: Brimstone)" },
        [0x02] = { "@Sniff Spot #444/(Vanilla: Bone)" },
        [0x01] = { "@Sniff Spot #445/(Vanilla: Bone)" },
    },
    [0x7E22B5] = {
        [0x01] = { "@Sniff Spot #375/(Vanilla: Ethanol)" },
        [0x02] = { "@Sniff Spot #376/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #377/(Vanilla: Limestone)" },
        [0x08] = { "@Sniff Spot #378/(Vanilla: Limestone)" },
        [0x10] = { "@Sniff Spot #379/(Vanilla: Wax)" },
        [0x20] = { "@Sniff Spot #380/(Vanilla: Wax)" },
        [0x40] = { "@Sniff Spot #381/(Vanilla: Wax)" },
        [0x80] = { "@Sniff Spot #382/(Vanilla: Vinegar)" },
    },
    [0x7E22BA] = {
        [0x20] = { "@Sniff Spot #386/(Vanilla: Ethanol)" },
        [0x10] = { "@Sniff Spot #400/(Vanilla: Crystal)" },
        [0x08] = { "@Sniff Spot #401/(Vanilla: Clay)" },
        [0x80] = { "@Sniff Spot #402/(Vanilla: Root)" },
        [0x40] = { "@Sniff Spot #403/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #404/(Vanilla: Clay)" },
        [0x02] = { "@Sniff Spot #405/(Vanilla: Oil)" },
        [0x01] = { "@Sniff Spot #426/(Vanilla: Ash)" },
    },
    [0x7E22BB] = {
        [0x01] = { "@Sniff Spot #387/(Vanilla: Root)" },
        [0x08] = { "@Sniff Spot #388/(Vanilla: Wax)" },
        [0x02] = { "@Sniff Spot #389/(Vanilla: Limestone)" },
        [0x04] = { "@Sniff Spot #390/(Vanilla: Limestone)" },
        [0x20] = { "@Sniff Spot #391/(Vanilla: Water)" },
        [0x40] = { "@Sniff Spot #392/(Vanilla: Vinegar)" },
        [0x80] = { "@Sniff Spot #393/(Vanilla: Ash)" },
        [0x10] = { "@Sniff Spot #399/(Vanilla: Water)" },
    },
    [0x7E22BC] = {
        [0x01] = { "@Sniff Spot #394/(Vanilla: Bone)" },
        [0x02] = { "@Sniff Spot #395/(Vanilla: Bone)" },
        [0x04] = { "@Sniff Spot #396/(Vanilla: Bone)" },
        [0x08] = { "@Sniff Spot #397/(Vanilla: Brimstone)" },
        [0x10] = { "@Sniff Spot #398/(Vanilla: Brimstone)" },
        [0x80] = { "@Sniff Spot #470/(Vanilla: Oil)" },
        [0x40] = { "@Sniff Spot #471/(Vanilla: Oil)" },
        [0x20] = { "@Sniff Spot #472/(Vanilla: Oil)" },
    },
    [0x7E22C3] = {
        [0x10] = { "@Sniff Spot #406/(Vanilla: Wax)" },
        [0x20] = { "@Sniff Spot #407/(Vanilla: Wax)" },
        [0x40] = { "@Sniff Spot #408/(Vanilla: Wax)" },
        [0x80] = { "@Sniff Spot #409/(Vanilla: Wax)" },
        [0x08] = { "@Sniff Spot #581/(Vanilla: Brimstone)" },
        [0x04] = { "@Sniff Spot #582/(Vanilla: Brimstone)" },
        [0x02] = { "@Sniff Spot #583/(Vanilla: Wax)" },
        [0x01] = { "@Sniff Spot #584/(Vanilla: Crystal)" },
    },
    [0x7E22C4] = {
        [0x01] = { "@Sniff Spot #410/(Vanilla: Ash)" },
        [0x02] = { "@Sniff Spot #411/(Vanilla: Ash)" },
        [0x04] = { "@Sniff Spot #412/(Vanilla: Bone)" },
        [0x08] = { "@Sniff Spot #413/(Vanilla: Bone)" },
        [0x10] = { "@Sniff Spot #414/(Vanilla: Bone)" },
        [0x20] = { "@Sniff Spot #415/(Vanilla: Brimstone)" },
        [0x40] = { "@Sniff Spot #416/(Vanilla: Brimstone)" },
        [0x80] = { "@Sniff Spot #417/(Vanilla: Brimstone)" },
    },
    [0x7E22C5] = {
        [0x01] = { "@Sniff Spot #418/(Vanilla: Brimstone)" },
        [0x02] = { "@Sniff Spot #419/(Vanilla: Water)" },
        [0x08] = { "@Sniff Spot #421/(Vanilla: Limestone)" },
        [0x10] = { "@Sniff Spot #422/(Vanilla: Root)" },
        [0x20] = { "@Sniff Spot #423/(Vanilla: Root)" },
        [0x40] = { "@Sniff Spot #424/(Vanilla: Root)" },
        [0x80] = { "@Sniff Spot #425/(Vanilla: Vinegar)" },
    },
    [0x7E22B9] = {
        [0x80] = { "@Sniff Spot #427/(Vanilla: Ash)" },
        [0x40] = { "@Sniff Spot #428/(Vanilla: Ash)" },
        [0x20] = { "@Sniff Spot #429/(Vanilla: Ethanol)" },
        [0x10] = { "@Sniff Spot #430/(Vanilla: Ethanol)" },
        [0x08] = { "@Sniff Spot #431/(Vanilla: Ethanol)" },
        [0x04] = { "@Sniff Spot #432/(Vanilla: Bone)" },
        [0x02] = { "@Sniff Spot #433/(Vanilla: Bone)" },
        [0x01] = { "@Sniff Spot #434/(Vanilla: Bone)" },
    },
    [0x7E22BF] = {
        [0x80] = { "@Sniff Spot #446/(Vanilla: Bone)" },
        [0x40] = { "@Sniff Spot #447/(Vanilla: Ash)" },
        [0x20] = { "@Sniff Spot #448/(Vanilla: Vinegar)" },
        [0x10] = { "@Sniff Spot #449/(Vanilla: Vinegar)" },
        [0x08] = { "@Sniff Spot #450/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #451/(Vanilla: Water)" },
        [0x02] = { "@Sniff Spot #452/(Vanilla: Water)" },
        [0x01] = { "@Sniff Spot #453/(Vanilla: Water)" },
    },
    [0x7E22BE] = {
        [0x80] = { "@Sniff Spot #454/(Vanilla: Wax)" },
        [0x40] = { "@Sniff Spot #455/(Vanilla: Wax)" },
        [0x20] = { "@Sniff Spot #456/(Vanilla: Limestone)" },
        [0x10] = { "@Sniff Spot #457/(Vanilla: Limestone)" },
        [0x08] = { "@Sniff Spot #458/(Vanilla: Limestone)" },
        [0x04] = { "@Sniff Spot #459/(Vanilla: Limestone)" },
        [0x02] = { "@Sniff Spot #460/(Vanilla: Root)" },
        [0x01] = { "@Sniff Spot #461/(Vanilla: Ethanol)" },
    },
    [0x7E22BD] = {
        [0x80] = { "@Sniff Spot #462/(Vanilla: Ethanol)" },
        [0x40] = { "@Sniff Spot #463/(Vanilla: Ethanol)" },
        [0x20] = { "@Sniff Spot #464/(Vanilla: Crystal)" },
        [0x10] = { "@Sniff Spot #465/(Vanilla: Crystal)" },
        [0x08] = { "@Sniff Spot #466/(Vanilla: Clay)" },
        [0x04] = { "@Sniff Spot #467/(Vanilla: Clay)" },
        [0x02] = { "@Sniff Spot #468/(Vanilla: Clay)" },
        [0x01] = { "@Sniff Spot #469/(Vanilla: Clay)" },
    },
    [0x7E22D7] = {
        [0x20] = { "@Sniff Spot #473/(Vanilla: Water)" },
        [0x10] = { "@Sniff Spot #474/(Vanilla: Water)" },
        [0x08] = { "@Sniff Spot #475/(Vanilla: Acorn)" },
        [0x04] = { "@Sniff Spot #476/(Vanilla: Acorn)" },
        [0x02] = { "@Sniff Spot #477/(Vanilla: Mushroom)" },
        [0x01] = { "@Sniff Spot #478/(Vanilla: Mushroom)" },
    },
    [0x7E22D6] = {
        [0x80] = { "@Sniff Spot #479/(Vanilla: Root)" },
        [0x40] = { "@Sniff Spot #480/(Vanilla: Root)" },
        [0x20] = { "@Sniff Spot #481/(Vanilla: Feather)" },
        [0x10] = { "@Sniff Spot #482/(Vanilla: Feather)" },
        [0x08] = { "@Sniff Spot #483/(Vanilla: Feather)" },
        [0x04] = { "@Sniff Spot #484/(Vanilla: Iron)" },
        [0x02] = { "@Sniff Spot #485/(Vanilla: Iron)" },
        [0x01] = { "@Sniff Spot #486/(Vanilla: Ash)" },
    },
    [0x7E22D5] = {
        [0x80] = { "@Sniff Spot #487/(Vanilla: Ash)" },
        [0x40] = { "@Sniff Spot #488/(Vanilla: Ethanol)" },
        [0x20] = { "@Sniff Spot #489/(Vanilla: Ethanol)" },
        [0x10] = { "@Sniff Spot #490/(Vanilla: Ethanol)" },
        [0x08] = { "@Sniff Spot #567/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #568/(Vanilla: Water)" },
        [0x02] = { "@Sniff Spot #569/(Vanilla: Acorn)" },
        [0x01] = { "@Sniff Spot #570/(Vanilla: Acorn)" },
    },
    [0x7E22C8] = {
        [0x02] = { "@Sniff Spot #491/(Vanilla: Mushroom)" },
        [0x10] = { "@Sniff Spot #492/(Vanilla: Iron)" },
        [0x40] = { "@Sniff Spot #495/(Vanilla: Feather)" },
        [0x04] = { "@Sniff Spot #498/(Vanilla: Mushroom)" },
        [0x20] = { "@Sniff Spot #499/(Vanilla: Iron)" },
        [0x80] = { "@Sniff Spot #501/(Vanilla: Feather)" },
        [0x08] = { "@Sniff Spot #504/(Vanilla: Mushroom)" },
        [0x01] = { "@Sniff Spot #506/(Vanilla: Ash)" },
    },
    [0x7E22C9] = {
        [0x40] = { "@Sniff Spot #493/(Vanilla: Brimstone)" },
        [0x02] = { "@Sniff Spot #494/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #496/(Vanilla: Root)" },
        [0x80] = { "@Sniff Spot #497/(Vanilla: Brimstone)" },
        [0x20] = { "@Sniff Spot #500/(Vanilla: Ash)" },
        [0x10] = { "@Sniff Spot #502/(Vanilla: Acorn)" },
        [0x08] = { "@Sniff Spot #503/(Vanilla: Root)" },
        [0x01] = { "@Sniff Spot #505/(Vanilla: Feather)" },
    },
    [0x7E22C7] = {
        [0x80] = { "@Sniff Spot #507/(Vanilla: Ash)" },
        [0x40] = { "@Sniff Spot #508/(Vanilla: Ethanol)" },
        [0x20] = { "@Sniff Spot #509/(Vanilla: Root)" },
        [0x10] = { "@Sniff Spot #510/(Vanilla: Root)" },
        [0x08] = { "@Sniff Spot #511/(Vanilla: Water)" },
        [0x04] = { "@Sniff Spot #512/(Vanilla: Brimstone)" },
        [0x02] = { "@Sniff Spot #513/(Vanilla: Feather)" },
        [0x01] = { "@Sniff Spot #514/(Vanilla: Feather)" },
    },
    [0x7E22C6] = {
        [0x80] = { "@Sniff Spot #515/(Vanilla: Mushroom)" },
        [0x40] = { "@Sniff Spot #516/(Vanilla: Mushroom)" },
        [0x20] = { "@Sniff Spot #517/(Vanilla: Mushroom)" },
        [0x10] = { "@Sniff Spot #518/(Vanilla: Acorn)" },
        [0x08] = { "@Sniff Spot #519/(Vanilla: Acorn)" },
        [0x04] = { "@Sniff Spot #520/(Vanilla: Iron)" },
        [0x02] = { "@Sniff Spot #521/(Vanilla: Iron)" },
    },
    [0x7E22CC] = {
        [0x04] = { "@Sniff Spot #522/(Vanilla: Water)" },
        [0x02] = { "@Sniff Spot #523/(Vanilla: Water)" },
        [0x01] = { "@Sniff Spot #524/(Vanilla: Ash)" },
        [0x80] = { "@Sniff Spot #562/(Vanilla: Acorn)" },
        [0x40] = { "@Sniff Spot #563/(Vanilla: Acorn)" },
        [0x20] = { "@Sniff Spot #564/(Vanilla: Acorn)" },
        [0x10] = { "@Sniff Spot #565/(Vanilla: Iron)" },
        [0x08] = { "@Sniff Spot #566/(Vanilla: Iron)" },
    },
    [0x7E22CB] = {
        [0x80] = { "@Sniff Spot #525/(Vanilla: Ash)" },
        [0x40] = { "@Sniff Spot #526/(Vanilla: Root)" },
        [0x20] = { "@Sniff Spot #527/(Vanilla: Root)" },
        [0x10] = { "@Sniff Spot #528/(Vanilla: Root)" },
        [0x08] = { "@Sniff Spot #529/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #530/(Vanilla: Brimstone)" },
        [0x02] = { "@Sniff Spot #531/(Vanilla: Brimstone)" },
        [0x01] = { "@Sniff Spot #532/(Vanilla: Brimstone)" },
    },
    [0x7E22CA] = {
        [0x40] = { "@Sniff Spot #533/(Vanilla: Iron)" },
        [0x20] = { "@Sniff Spot #534/(Vanilla: Iron)" },
        [0x80] = { "@Sniff Spot #535/(Vanilla: Feather)" },
        [0x10] = { "@Sniff Spot #536/(Vanilla: Acorn)" },
        [0x08] = { "@Sniff Spot #537/(Vanilla: Acorn)" },
        [0x04] = { "@Sniff Spot #538/(Vanilla: Acorn)" },
        [0x02] = { "@Sniff Spot #539/(Vanilla: Mushroom)" },
        [0x01] = { "@Sniff Spot #540/(Vanilla: Mushroom)" },
    },
    [0x7E22D8] = {
        [0x04] = { "@Sniff Spot #541/(Vanilla: Iron Bracer)" },
    },
    [0x7E22CE] = {
        [0x80] = { "@Sniff Spot #546/(Vanilla: Water)" },
        [0x40] = { "@Sniff Spot #547/(Vanilla: Water)" },
        [0x20] = { "@Sniff Spot #548/(Vanilla: Ash)" },
        [0x10] = { "@Sniff Spot #549/(Vanilla: Ash)" },
        [0x08] = { "@Sniff Spot #550/(Vanilla: Root)" },
        [0x04] = { "@Sniff Spot #551/(Vanilla: Root)" },
        [0x02] = { "@Sniff Spot #552/(Vanilla: Root)" },
        [0x01] = { "@Sniff Spot #553/(Vanilla: Root)" },
    },
    [0x7E22CD] = {
        [0x80] = { "@Sniff Spot #554/(Vanilla: Feather)" },
        [0x40] = { "@Sniff Spot #555/(Vanilla: Feather)" },
        [0x20] = { "@Sniff Spot #556/(Vanilla: Feather)" },
        [0x10] = { "@Sniff Spot #557/(Vanilla: Brimstone)" },
        [0x08] = { "@Sniff Spot #558/(Vanilla: Brimstone)" },
        [0x04] = { "@Sniff Spot #559/(Vanilla: Brimstone)" },
        [0x02] = { "@Sniff Spot #560/(Vanilla: Mushroom)" },
        [0x01] = { "@Sniff Spot #561/(Vanilla: Mushroom)" },
    },
    [0x7E22D4] = {
        [0x80] = { "@Sniff Spot #571/(Vanilla: Acorn)" },
        [0x40] = { "@Sniff Spot #572/(Vanilla: Feather)" },
        [0x20] = { "@Sniff Spot #573/(Vanilla: Feather)" },
        [0x10] = { "@Sniff Spot #574/(Vanilla: Feather)" },
        [0x08] = { "@Sniff Spot #575/(Vanilla: Ethanol)" },
        [0x04] = { "@Sniff Spot #576/(Vanilla: Ethanol)" },
        [0x02] = { "@Sniff Spot #577/(Vanilla: Ash)" },
        [0x01] = { "@Sniff Spot #578/(Vanilla: Ash)" },
    },
    [0x7E22C2] = {
        [0x80] = { "@Sniff Spot #585/(Vanilla: Iron)" },
        [0x40] = { "@Sniff Spot #586/(Vanilla: Iron)" },
        [0x20] = { "@Sniff Spot #587/(Vanilla: Dry Ice)" },
        [0x10] = { "@Sniff Spot #588/(Vanilla: Meteorite)" },
        [0x08] = { "@Sniff Spot #589/(Vanilla: Grease)" },
        [0x04] = { "@Sniff Spot #590/(Vanilla: Grease)" },
        [0x02] = { "@Sniff Spot #591/(Vanilla: Gunpowder)" },
        [0x01] = { "@Sniff Spot #592/(Vanilla: Gunpowder)" },
    },
}
SNIFF_MAPPING_OVERWORLD = {
    [0x7E228F] = {
        [0x10] = { "@Act 1/Southern Jungle/Sniff Spots behind bushes" },
        [0x08] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x20] = { "@Act 1/Southern Jungle/Sniff Spots behind bushes" },
        [0x80] = { "@Act 1/Southern Jungle/Sniff Spots behind bushes" },
        [0x40] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x04] = { "@Act 1/Swamp/Sniff Spots" },
        [0x02] = { "@Act 1/Swamp/Sniff Spots" },
    },
    [0x7E2291] = {
        [0x02] = { "@Act 1/Southern Jungle/Sniff Spots behind bushes" },
        [0x01] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x80] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x40] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x20] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x08] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x04] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x10] = { "@Act 1/Southern Jungle/Sniff Spots" },
    },
    [0x7E2290] = {
        [0x10] = { "@Act 1/Southern Jungle/Sniff Spots behind bushes" },
        [0x80] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x08] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x04] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x02] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x40] = { "@Act 1/Southern Jungle/Sniff Spots behind bushes" },
        [0x01] = { "@Act 1/Southern Jungle/Sniff Spots" },
    },
    [0x7E2292] = {
        [0x08] = { "@Act 1/Southern Jungle/Sniff Spots behind bushes" },
        [0x04] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x02] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x01] = { "@Act 1/Southern Jungle/Sniff Spots" },
        [0x20] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
        [0x40] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
        [0x80] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
    },
    [0x7E2293] = {
        [0x08] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
        [0x04] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
        [0x80] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
        [0x02] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
        [0x40] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
        [0x01] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
        [0x20] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
        [0x10] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
    },
    [0x7E2294] = {
        [0x10] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
        [0x08] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
        [0x01] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
        [0x04] = { "@Act 1/Fire Eyes' Village/Sniff Spots" },
        [0x80] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x40] = { "@Act 1/Quick Sand Fields/Sniff Spots behind bushes" },
        [0x20] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
    },
    [0x7E2296] = {
        [0x04] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x02] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x01] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x08] = { "@Act 1/Quick Sand Fields/Sniff Spots behind Thraxx or bushes" },
        [0x10] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x20] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x40] = { "@Act 1/Quick Sand Fields/Sniff Spots behind Thraxx or bushes" },
        [0x80] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
    },
    [0x7E2295] = {
        [0x02] = { "@Act 1/Quick Sand Fields/Sniff Spots behind bushes" },
        [0x01] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x40] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x20] = { "@Act 1/Quick Sand Fields/Sniff Spots behind bushes" },
        [0x10] = { "@Act 1/Quick Sand Fields/Sniff Spots behind bushes" },
        [0x08] = { "@Act 1/Quick Sand Fields/Sniff Spots behind bushes" },
        [0x04] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x80] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
    },
    [0x7E2297] = {
        [0x20] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x10] = { "@Act 1/Quick Sand Fields/Sniff Spots behind Thraxx or bushes" },
        [0x08] = { "@Act 1/Quick Sand Fields/Sniff Spots behind Thraxx or bushes" },
        [0x04] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x01] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x02] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x40] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x80] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
    },
    [0x7E2298] = {
        [0x01] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x02] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x04] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x08] = { "@Act 1/Quick Sand Fields/Sniff Spots behind Thraxx or bushes" },
        [0x10] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
        [0x20] = { "@Act 1/Quick Sand Fields/Sniff Spots behind Thraxx or bushes" },
        [0x80] = { "@Act 1/Quick Sand Fields/Sniff Spots" },
    },
    [0x7E2299] = {
        [0x01] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x02] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x04] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x08] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x10] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x20] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x40] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x80] = { "@Act 1/Bugmuck/Sniff Spots behind Thraxx or bushes" },
    },
    [0x7E229A] = {
        [0x01] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x02] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x04] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x08] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x10] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x20] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x40] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x80] = { "@Act 1/Bugmuck/Sniff Spots behind Thraxx or bushes" },
    },
    [0x7E229B] = {
        [0x01] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x02] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x04] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x08] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x10] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x20] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x40] = { "@Act 1/Bugmuck/Sniff Spots behind Thraxx or bushes" },
        [0x80] = { "@Act 1/Bugmuck/Sniff Spots" },
    },
    [0x7E229C] = {
        [0x08] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x01] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x02] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x04] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x10] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x20] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x40] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x80] = { "@Act 1/Bugmuck/Sniff Spots" },
    },
    [0x7E229D] = {
        [0x01] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x02] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x04] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x08] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x10] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x20] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x40] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x80] = { "@Act 1/Bugmuck/Sniff Spots" },
    },
    [0x7E229E] = {
        [0x01] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x02] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x04] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x08] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x20] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x10] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x40] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x80] = { "@Act 1/Bugmuck/Sniff Spots" },
    },
    [0x7E229F] = {
        [0x01] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x02] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x04] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x08] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x10] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x20] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x40] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x80] = { "@Act 1/Bugmuck/Sniff Spots" },
    },
    [0x7E22A0] = {
        [0x01] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x02] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x04] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x08] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x10] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x20] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x40] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x80] = { "@Act 1/Bugmuck/Sniff Spots" },
    },
    [0x7E22A1] = {
        [0x01] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x02] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x04] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x08] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x10] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x20] = { "@Act 1/Bugmuck/Sniff Spots" },
        [0x40] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x80] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
    },
    [0x7E22A2] = {
        [0x01] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x02] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x04] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x08] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x10] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x20] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x40] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x80] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
    },
    [0x7E22A3] = {
        [0x01] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x02] = { "@Act 1/Northern Jungle/Sniff Spots" },
        [0x04] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x08] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x10] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x20] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x40] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x80] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
    },
    [0x7E22A4] = {
        [0x01] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x02] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x04] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x80] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x10] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x08] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x20] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x40] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
    },
    [0x7E22A7] = {
        [0x10] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x08] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x02] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x01] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x04] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x80] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x40] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x20] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
    },
    [0x7E22A6] = {
        [0x40] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x80] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x10] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x04] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x20] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x08] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x02] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x01] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
    },
    [0x7E22A8] = {
        [0x01] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x02] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x04] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x08] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x10] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x20] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x40] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x80] = { "@Act 1/Volcano Path/Sniff Spots" },
    },
    [0x7E22A5] = {
        [0x02] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x40] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x04] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x80] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x01] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x20] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x10] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x08] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
    },
    [0x7E22A9] = {
        [0x01] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x02] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x04] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x08] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x10] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x40] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x20] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x80] = { "@Act 1/Volcano Path/Sniff Spots" },
    },
    [0x7E22AA] = {
        [0x01] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x80] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x40] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x20] = { "@Act 1/Volcano Path/Sniff Spots behind non-sword" },
        [0x10] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x08] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x04] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x02] = { "@Act 1/Volcano Path/Sniff Spots" },
    },
    [0x7E22AB] = {
        [0x01] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x02] = { "@Act 1/Volcano Path/Sniff Spots behind non-sword" },
        [0x04] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x08] = { "@Act 1/Volcano Path/Sniff Spots" },
        [0x80] = { "@Act 1/Volcano Core/Sniff Spots" },
    },
    [0x7E22B3] = {
        [0x01] = { "@Act 1/Swamp/Sniff Spots" },
        [0x80] = { "@Act 1/Swamp/Sniff Spots" },
        [0x40] = { "@Act 1/Swamp/Sniff Spots" },
        [0x20] = { "@Act 1/Swamp/Sniff Spots" },
        [0x10] = { "@Act 1/Swamp/Sniff Spots" },
        [0x02] = { "@Act 1/Swamp/Sniff Spots" },
        [0x04] = { "@Act 1/Swamp/Sniff Spots" },
        [0x08] = { "@Act 1/Swamp/Sniff Spots" },
    },
    [0x7E22B2] = {
        [0x80] = { "@Act 1/Swamp/Sniff Spots" },
    },
    [0x7E22B4] = {
        [0x01] = { "@Act 1/Swamp/Sniff Spots" },
        [0x20] = { "@Act 2/Crustacia/hidden Sniff Spots behind Levitate" },
        [0x40] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x80] = { "@Act 2/Crustacia/Sniff Spots" },
    },
    [0x7E228E] = {
        [0x20] = { "@Act 1/Swamp/Sniff Spots" },
        [0x40] = { "@Act 1/Swamp/Sniff Spots" },
        [0x01] = { "@Act 1/Swamp/Sniff Spots" },
        [0x02] = { "@Act 1/Swamp/Sniff Spots" },
        [0x04] = { "@Act 1/Swamp/Sniff Spots" },
        [0x80] = { "@Act 1/Swamp/Sniff Spots" },
        [0x08] = { "@Act 1/Swamp/Sniff Spots" },
        [0x10] = { "@Act 1/Swamp/Sniff Spots" },
    },
    [0x7E228C] = {
        [0x04] = { "@Act 1/Swamp/Sniff Spots" },
        [0x01] = { "@Act 1/Swamp/Sniff Spots" },
        [0x02] = { "@Act 1/Swamp/Sniff Spots" },
        [0x08] = { "@Act 1/Swamp/Sniff Spots" },
        [0x10] = { "@Act 1/Swamp/Sniff Spots" },
        [0x20] = { "@Act 1/Swamp/Sniff Spots" },
        [0x40] = { "@Act 1/Swamp/Sniff Spots" },
        [0x80] = { "@Act 1/Swamp/Sniff Spots" },
    },
    [0x7E228D] = {
        [0x10] = { "@Act 1/Swamp/Sniff Spots" },
        [0x20] = { "@Act 1/Swamp/Sniff Spots" },
        [0x40] = { "@Act 1/Swamp/Sniff Spots" },
        [0x80] = { "@Act 1/Swamp/Sniff Spots" },
        [0x02] = { "@Act 1/Swamp/Sniff Spots" },
        [0x04] = { "@Act 1/Swamp/Sniff Spots" },
        [0x08] = { "@Act 1/Swamp/Sniff Spots" },
    },
    [0x7E22B0] = {
        [0x04] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x01] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x02] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x08] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x10] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x20] = { "@Act 1/Volcano Core/Sniff Spots" },
    },
    [0x7E22AF] = {
        [0x01] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x02] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x04] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x08] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x10] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x20] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x40] = { "@Act 1/Northern Jungle/Sniff Spots behind bushes" },
        [0x80] = { "@Act 1/Volcano Core/Sniff Spots" },
    },
    [0x7E22AC] = {
        [0x08] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x04] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x02] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x01] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x10] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x20] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x40] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x80] = { "@Act 1/Volcano Core/Sniff Spots" },
    },
    [0x7E22AD] = {
        [0x01] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x02] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x04] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x08] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x10] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x20] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x40] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x80] = { "@Act 1/Volcano Core/Sniff Spots" },
    },
    [0x7E22AE] = {
        [0x01] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x02] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x04] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x08] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x10] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x20] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x40] = { "@Act 1/Volcano Core/Sniff Spots" },
        [0x80] = { "@Act 1/Volcano Core/Sniff Spots" },
    },
    [0x7E22D3] = {
        [0x08] = { "@Act 1/Quick Sand Fields/Sniff Spots behind bushes" },
        [0x04] = { "@Act 1/Quick Sand Fields/Sniff Spots behind bushes" },
        [0x20] = { "@Act 1/Quick Sand Fields/Sniff Spots behind bushes" },
        [0x10] = { "@Act 1/Quick Sand Fields/Sniff Spots behind bushes" },
        [0x01] = { "@Act 2/Crustacia/Sniff Spots behind Bronze Axe or higher" },
        [0x02] = { "@Act 2/Crustacia/Sniff Spots behind Bronze Axe or higher" },
        [0x80] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x40] = { "@Act 3/Ivor Tower/Sniff Spots" },
    },
    [0x7E22D1] = {
        [0x01] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x02] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x04] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x08] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x10] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x20] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x40] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x80] = { "@Act 2/Crustacia/Sniff Spots" },
    },
    [0x7E22D0] = {
        [0x80] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x40] = { "@Act 2/Nobilia/Sniff Spots behind Aegis" },
        [0x20] = { "@Act 2/Nobilia/Sniff Spots behind Aegis" },
        [0x10] = { "@Act 2/Nobilia/Sniff Spots behind Aegis" },
        [0x08] = { "@Act 2/Nobilia/Sniff Spots behind Aegis" },
        [0x04] = { "@Act 2/Nobilia/Sniff Spots behind Aegis" },
        [0x02] = { "@Act 2/Nobilia/Sniff Spots behind Aegis" },
        [0x01] = { "@Act 2/Nobilia/Sniff Spots behind Aegis" },
    },
    [0x7E22CF] = {
        [0x40] = { "@Act 2/Nobilia/Sniff Spots behind Aegis" },
        [0x20] = { "@Act 2/Nobilia/Sniff Spots behind Aegis" },
        [0x80] = { "@Act 2/Nobilia/Sniff Spots behind Aegis" },
        [0x08] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x04] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x02] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x01] = { "@Act 3/Ivor Tower/Sniff Spots" },
    },
    [0x7E22B6] = {
        [0x08] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x10] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x20] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x40] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x80] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x01] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x02] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x04] = { "@Act 2/Crustacia/hidden Sniff Spots behind Levitate" },
    },
    [0x7E22B7] = {
        [0x01] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x02] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x04] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x08] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x10] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x20] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x40] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x80] = { "@Act 2/Nobilia/Sniff Spots" },
    },
    [0x7E22B8] = {
        [0x01] = { "@Act 2/Nobilia/Sniff Spots" },
        [0x80] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x40] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x20] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x10] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x08] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x04] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x02] = { "@Act 2/Halls of Collosia/Sniff Spots" },
    },
    [0x7E22D2] = {
        [0x01] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x02] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x04] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x08] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x10] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x20] = { "@Act 2/Crustacia/Sniff Spots behind Bronze Axe or higher" },
        [0x40] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x80] = { "@Act 2/Crustacia/Sniff Spots behind Bronze Axe or higher" },
    },
    [0x7E22C1] = {
        [0x80] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x40] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x20] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x10] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x08] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x04] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x02] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x01] = { "@Act 2/Crustacia/Sniff Spots" },
    },
    [0x7E22C0] = {
        [0x80] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x40] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x20] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x10] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x08] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x04] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x02] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x01] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
    },
    [0x7E22B5] = {
        [0x01] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x02] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x04] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x08] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x10] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x20] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x40] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x80] = { "@Act 2/Crustacia/Sniff Spots" },
    },
    [0x7E22BA] = {
        [0x20] = { "@Act 2/Crustacia/hidden Sniff Spots" },
        [0x10] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x08] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x80] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x40] = { "@Act 2/Crustacia/hidden Sniff Spots" },
        [0x04] = { "@Act 2/Crustacia/hidden Sniff Spots" },
        [0x02] = { "@Act 2/Crustacia/hidden Sniff Spots" },
        [0x01] = { "@Act 2/Halls of Collosia/Sniff Spots" },
    },
    [0x7E22BB] = {
        [0x01] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x08] = { "@Act 2/Crustacia/hidden Sniff Spots" },
        [0x02] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x04] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x20] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x40] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x80] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x10] = { "@Act 2/Crustacia/Sniff Spots" },
    },
    [0x7E22BC] = {
        [0x01] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x02] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x04] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x08] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x10] = { "@Act 2/Crustacia/Sniff Spots" },
        [0x80] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x40] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x20] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
    },
    [0x7E22C3] = {
        [0x10] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x20] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x40] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x80] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x08] = { "@Act 4/Omnitopia/Sniff Spots" },
        [0x04] = { "@Act 4/Omnitopia/Sniff Spots" },
        [0x02] = { "@Act 4/Omnitopia/Sniff Spots" },
        [0x01] = { "@Act 4/Omnitopia/Sniff Spots" },
    },
    [0x7E22C4] = {
        [0x01] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x02] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x04] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x08] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x10] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x20] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x40] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x80] = { "@Act 2/Pyramid/Sniff Spots" },
    },
    [0x7E22C5] = {
        [0x01] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x02] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x08] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x10] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x20] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x40] = { "@Act 2/Pyramid/Sniff Spots" },
        [0x80] = { "@Act 2/Pyramid/Sniff Spots" },
    },
    [0x7E22B9] = {
        [0x80] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x40] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x20] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x10] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x08] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x04] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x02] = { "@Act 2/Halls of Collosia/Sniff Spots" },
        [0x01] = { "@Act 2/Halls of Collosia/Sniff Spots" },
    },
    [0x7E22BF] = {
        [0x80] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x40] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x20] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x10] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x08] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x04] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x02] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x01] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
    },
    [0x7E22BE] = {
        [0x80] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x40] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x20] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x10] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x08] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x04] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x02] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x01] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
    },
    [0x7E22BD] = {
        [0x80] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x40] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x20] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x10] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x08] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x04] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x02] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
        [0x01] = { "@Act 2/Oglin Tunnel/Sniff Spots" },
    },
    [0x7E22D7] = {
        [0x20] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x10] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x08] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x04] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x02] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x01] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
    },
    [0x7E22D6] = {
        [0x80] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x40] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x20] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x10] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x08] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x04] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x02] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x01] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
    },
    [0x7E22D5] = {
        [0x80] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x40] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x20] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x10] = { "@Act 3/Dark Forest/Sniff Spots behind Knight Basher" },
        [0x08] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x04] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x02] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x01] = { "@Act 3/Ivor Tower/Sniff Spots" },
    },
    [0x7E22C8] = {
        [0x02] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x10] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x40] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x04] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x20] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x80] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x08] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x01] = { "@Act 3/Ivor Tower/Sniff Spots" },
    },
    [0x7E22C9] = {
        [0x40] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x02] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x04] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x80] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x20] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x10] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x08] = { "@Act 3/Dark Forest/Sniff Spots" },
        [0x01] = { "@Act 3/Dark Forest/Sniff Spots" },
    },
    [0x7E22C7] = {
        [0x80] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x40] = { "@Act 3/Ivor Tower/hidden Sniff Spots" },
        [0x20] = { "@Act 3/Ivor Tower/hidden Sniff Spots" },
        [0x10] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x08] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x04] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x02] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x01] = { "@Act 3/Ivor Tower/Sniff Spots" },
    },
    [0x7E22C6] = {
        [0x80] = { "@Act 3/Ivor Tower/hidden Sniff Spots" },
        [0x40] = { "@Act 3/Ivor Tower/hidden Sniff Spots" },
        [0x20] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x10] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x08] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x04] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x02] = { "@Act 3/Ivor Tower/Sniff Spots" },
    },
    [0x7E22CC] = {
        [0x04] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x02] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x01] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x80] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x40] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x20] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x10] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x08] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
    },
    [0x7E22CB] = {
        [0x80] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x40] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x20] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x10] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x08] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x04] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x02] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x01] = { "@Act 3/Chessboard/Sniff Spots" },
    },
    [0x7E22CA] = {
        [0x40] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x20] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x80] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x10] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x08] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x04] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x02] = { "@Act 3/Chessboard/Sniff Spots" },
        [0x01] = { "@Act 3/Chessboard/Sniff Spots" },
    },
    [0x7E22D8] = {
        [0x04] = { "@Act 3/Ivor Tower/Sniff Spots" },
    },
    [0x7E22CE] = {
        [0x80] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x40] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x20] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x10] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x08] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x04] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x02] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x01] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
    },
    [0x7E22CD] = {
        [0x80] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x40] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x20] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x10] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x08] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x04] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x02] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
        [0x01] = { "@Act 3/Ivor Tower/Sniff Spots behind Queen's Key" },
    },
    [0x7E22D4] = {
        [0x80] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x40] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x20] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x10] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x08] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x04] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x02] = { "@Act 3/Ivor Tower/Sniff Spots" },
        [0x01] = { "@Act 3/Ivor Tower/Sniff Spots" },
    },
    [0x7E22C2] = {
        [0x80] = { "@Act 4/Omnitopia/Sniff Spots" },
        [0x40] = { "@Act 4/Omnitopia/Sniff Spots" },
        [0x20] = { "@Act 4/Omnitopia/Sniff Spots" },
        [0x10] = { "@Act 4/Omnitopia/Sniff Spots" },
        [0x08] = { "@Act 4/Omnitopia/Sniff Spots" },
        [0x04] = { "@Act 4/Omnitopia/Sniff Spots" },
        [0x02] = { "@Act 4/Omnitopia/Sniff Spots" },
        [0x01] = { "@Act 4/Omnitopia/Sniff Spots" },
    },
}
