name: Create Release ZIP

on:
  workflow_dispatch:  # Trigger the action manually

jobs:
  create_release_zip:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Extract package version from manifest.json
      - name: Extract package version
        id: get_version
        run: |
          PACKAGE_VERSION=$(jq -r '.package_version' manifest.json)
          PACKAGE_VERSION_UNDERSCORED=${PACKAGE_VERSION//./_}
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "PACKAGE_VERSION_UNDERSCORED=$PACKAGE_VERSION_UNDERSCORED" >> $GITHUB_ENV

      # Step 3: Remove unnecessary files and directories
      - name: Clean up unnecessary files
        run: |
          rm -rf gen
          rm -rf .github
          rm -rf .git
          rm .gitignore
          find . -name "*.xcf" -type f -delete  # Remove all .xcf files

      # Step 4: Create the ZIP file
      - name: Create release zip
        run: |
          ZIP_NAME="evermizer-tracker-package-v${{ env.PACKAGE_VERSION_UNDERSCORED }}.zip"
          zip -r $ZIP_NAME ./*

      # Step 5: Create a draft release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}  # Tag name is the version prefixed with 'v'
          release_name: v${{ env.PACKAGE_VERSION }}  # Release name is also prefixed with 'v'
          draft: true  # Create a draft release
          prerelease: false  # Set to true if it's a pre-release          

      # Step 6: Upload the ZIP file to the release
      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # Use the URL from the release creation step
          asset_path: evermizer-tracker-package-v${{ env.PACKAGE_VERSION_UNDERSCORED }}.zip
          asset_name: evermizer-tracker-package-v${{ env.PACKAGE_VERSION_UNDERSCORED }}.zip
          asset_content_type: application/zip
