name: Create or Update Release ZIP

on:
  workflow_dispatch:  # Trigger the action manually

jobs:
  create_or_update_release_zip:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install GitHub CLI
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      # Step 3: Extract package version from manifest.json
      - name: Extract package version
        id: get_version
        run: |
          PACKAGE_VERSION=$(jq -r '.package_version' manifest.json)
          PACKAGE_VERSION_UNDERSCORED=${PACKAGE_VERSION//./_}
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "PACKAGE_VERSION_UNDERSCORED=$PACKAGE_VERSION_UNDERSCORED" >> $GITHUB_ENV

      # Step 4: Check if release exists and is a draft (fail if release exists and is not a draft)
      - name: Check if release exists and is draft
        id: check_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v${{ env.PACKAGE_VERSION }}"
          
          # Check if the release exists using GitHub CLI
          echo "Checking for release with tag $TAG_NAME..."
          RELEASE_INFO=$(gh release view $TAG_NAME --json isDraft --jq '.isDraft' 2> /dev/null)
          EXIT_CODE=$?
          
          if [ $EXIT_CODE -ne  ]; then
            echo "No release found."
          else
            IS_DRAFT=$RELEASE_INFO
            echo "Release found: isDraft=$IS_DRAFT"
          
            # Fail if the release exists but is not a draft
            if [ "$IS_DRAFT" = "false" ]; then
              echo "Release with tag $TAG_NAME already exists and is not a draft. Failing the workflow."
              exit 1  # Fail the workflow if the release exists but is not a draft
            fi
          fi

      # Step 5: Remove unnecessary files and directories
      - name: Clean up unnecessary files
        run: |
          rm -rf gen
          rm -rf .github
          rm -rf .git
          rm .gitignore
          find . -name "*.xcf" -type f -delete  # Remove all .xcf files

      # Step 6: Create the ZIP file
      - name: Create release zip
        run: |
          ZIP_NAME="evermizer-tracker-package-v${{ env.PACKAGE_VERSION_UNDERSCORED }}.zip"
          zip -r $ZIP_NAME ./*         

      # Step 7: Create/Update Release with the ZIP file
      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          name: v${{ env.PACKAGE_VERSION }}
          target_commitish: 'main'
          draft: true
          generate_release_notes: true
          files: evermizer-tracker-package-v${{ env.PACKAGE_VERSION_UNDERSCORED }}.zip
          fail_on_unmatched_files: true
