name: Create or Update Release ZIP

on:
  workflow_dispatch:  # Trigger the action manually

jobs:
  create_or_update_release_zip:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install GitHub CLI
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      # Step 3: Extract package version from manifest.json
      - name: Extract package version
        id: get_version
        run: |
          PACKAGE_VERSION=$(jq -r '.package_version' manifest.json)
          PACKAGE_VERSION_UNDERSCORED=${PACKAGE_VERSION//./_}
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "PACKAGE_VERSION_UNDERSCORED=$PACKAGE_VERSION_UNDERSCORED" >> $GITHUB_ENV

      # Step 4: Remove unnecessary files and directories
      - name: Clean up unnecessary files
        run: |
          rm -rf gen
          rm -rf .github
          rm -rf .git
          rm .gitignore
          find . -name "*.xcf" -type f -delete  # Remove all .xcf files

      # Step 5: Create the ZIP file
      - name: Create release zip
        run: |
          ZIP_NAME="evermizer-tracker-package-v${{ env.PACKAGE_VERSION_UNDERSCORED }}.zip"
          zip -r $ZIP_NAME ./*         

      # Step 8: Create/Update Release with the ZIP file
      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          name: v${{ env.PACKAGE_VERSION }} 
          target_commitish: 'main'
          draft: true
          generate_release_notes: true
          files: evermizer-tracker-package-v${{ env.PACKAGE_VERSION_UNDERSCORED }}.zip
          fail_on_unmatched_files: true
