name: Discord webhook
on:
  release: 
    types: [published]

jobs:
  discord_webhook:    
    runs-on: ubuntu-latest    
    steps:
     - name: Discord Webhook Notify
       uses: Cyb3RGER/discord-webhook-notify@3d9f4d512184ce3cb014a86aaf0ab8cb93ae84b7
       with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
