name: Discord webhook
on:
  release: 
    types: [published]

jobs:
  discord_webhook:    
    runs-on: ubuntu-latest    
    steps:
     - name: Discord Webhook Notify
       uses: Cyb3RGER/discord-webhook-notify@c79db5a416063b6e50a3b3dea5a38d35f214521f
       with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
