name: Discord webhook
on:
  # Triggers the workflow on release events
  release:
    types: 
      - published
      - released
      - prereleased
      - edited
jobs:
  discord_webhook:    
    runs-on: ubuntu-latest    
    steps:
     - name: Discord Webhook Notify
       uses: rjstone/discord-webhook-notify@v1
       with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
