name: Discord webhook
on:
  release: 
    types: [published]

jobs:
  discord_webhook:    
    runs-on: ubuntu-latest    
    steps:
     - name: Discord Webhook Notify
       uses: Cyb3RGER/discord-webhook-notify@0927dcbf25e3c5cb36d628add3daef922d335bd6
       with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
        severity: info
        color: '#ff9900'
