name: Pack validation (strict)
on:
  workflow_dispatch:
  push:
    paths:
      - '!**.md'
  pull_request:
    paths:
      - '!**.md'
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate pack (strict)
        uses: PopTracker/pack-checker-action@v1
        with:
          strict: true