on:
  push
  
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.6.0
      - name: Validate pack (lax)
        uses: PopTracker/pack-checker-action@v1
      - name: Validate pack (strict)
        uses: PopTracker/pack-checker-action@v1
        with:
          strict: true
  
